all: print
	@make -C ../libft/ all
	@make -C ../src/init/ all
	@make -C ../src/operations/ all
	@make -C operations/ all
	@make -C ../lib/ unit_test

print:
	@echo \*\*\* Compiling unit tests

clean:
	@make -C ../ clean

fclean: clean
	@make -C ../ fclean
	